name: CI - build and test

on:                                
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:                           

    runs-on: ubuntu-latest         

    steps:    
    - name: Check out this repo
      uses: actions/checkout@v2                   
      with:
        fetch-depth: 0
    - name: Set up JDK 11                         
      uses: actions/setup-java@v2        
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew              
    - name: Build and test
      working-directory:
      run: ./gradlew build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.2.5  
      with:
        branch: gh-pages                                 
        folder: build/reports                            
    - name: Deploy reports using an SSH agent
      run: |
        eval $(ssh-agent -s -t 600)                           
        ssh-add <(echo "${{ secrets.REPORTS_SSH_KEY }}")      
        git config --global user.email "sallg001@odu.edu"      
        git config --global user.name "Project Actions
        ./gradlew deploySite                               